package Main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Gaco
 */
public class CrearCine extends javax.swing.JFrame {

    //Coordenadas del mouse (variables)
    int mouseX, mouseY;

    private User loggedInUser;

    LoginSystem LoginSystem = new LoginSystem();
    List<User> userList = LoginSystem.getUserList();

    //Método para obtener la instancia "real" de User desde LoginSystem
    public void getUserIndex() {
        int loggedInUserIndex = -1;
        for (int i = 0; i < userList.size(); i++) {
            if (userList.get(i).getUsername().equals(loggedInUser.getUsername())) {
                loggedInUserIndex = i;
                break;
            }
        }
        loggedInUser = userList.get(loggedInUserIndex);
    }

    public CrearCine(Main.User user) {
        loggedInUser = user;
        LoginSystem.readUsers();

        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/AppIcon.png")).getImage());
        this.setBackground(new Color(0, 0, 0, 0));

        UserField.setText(loggedInUser.getUsername());
        saveUserProfileImage(ImageLabel, "src/Images/Imagotipo Logo No BG.png", loggedInUser.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bar = new GUIresources.RoundPanel2();
        exitPanel = new GUIresources.RoundPanel2();
        exitLabel = new javax.swing.JLabel();
        Bg = new GUIresources.RoundPanel2();
        newUserLabel = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();
        ImagePanel = new GUIresources.RoundPanel2();
        ImageLabel = new javax.swing.JLabel();
        newUserLabel1 = new javax.swing.JLabel();
        CineField = new javax.swing.JTextField();
        UserLabel = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        UserLabel1 = new javax.swing.JLabel();
        Error1Text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bar.setColor(new java.awt.Color(75, 0, 216));
        Bar.setTopLeftRadius(13);
        Bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarMouseDragged(evt);
            }
        });
        Bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BarLayout = new javax.swing.GroupLayout(Bar);
        Bar.setLayout(BarLayout);
        BarLayout.setHorizontalGroup(
            BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        BarLayout.setVerticalGroup(
            BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(Bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 30));

        exitPanel.setColor(new java.awt.Color(75, 0, 216));
        exitPanel.setTopRightRadius(13);

        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 50, -1));

        Bg.setBottomLeftRadius(13);
        Bg.setBottomRightRadius(13);
        Bg.setColor(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newUserLabel.setFont(new java.awt.Font("Roboto", 0, 40)); // NOI18N
        newUserLabel.setForeground(new java.awt.Color(56, 48, 46));
        newUserLabel.setText("Bienvenido a CinemaCentr");
        newUserLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bg.add(newUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 480, -1));

        StartButton.setBackground(new java.awt.Color(75, 0, 216));
        StartButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        StartButton.setForeground(new java.awt.Color(255, 255, 255));
        StartButton.setText("Comenzar");
        StartButton.setBorderPainted(false);
        StartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        Bg.add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        ImagePanel.setColor(new java.awt.Color(75, 0, 216));
        ImagePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagePanel.setRadius(13);

        ImageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ImageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImageLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ImageLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        ImagePanelLayout.setVerticalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );

        Bg.add(ImagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        newUserLabel1.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        newUserLabel1.setForeground(new java.awt.Color(56, 48, 46));
        newUserLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cheque-de-dinero.png"))); // NOI18N
        newUserLabel1.setText("Nombre del cine");
        newUserLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        newUserLabel1.setIconTextGap(10);
        Bg.add(newUserLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 210, -1));

        CineField.setBackground(new java.awt.Color(242, 242, 242));
        CineField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        CineField.setForeground(new java.awt.Color(56, 48, 46));
        CineField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CineField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CineFieldActionPerformed(evt);
            }
        });
        Bg.add(CineField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 220, 25));

        UserLabel.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(56, 48, 46));
        UserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/imagen.png"))); // NOI18N
        UserLabel.setText("Imagen");
        UserLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        UserLabel.setIconTextGap(10);
        Bg.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 110, -1));

        UserField.setEditable(false);
        UserField.setBackground(new java.awt.Color(242, 242, 242));
        UserField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        UserField.setForeground(new java.awt.Color(56, 48, 46));
        UserField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UserField.setFocusable(false);
        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        Bg.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 220, 25));

        UserLabel1.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        UserLabel1.setForeground(new java.awt.Color(56, 48, 46));
        UserLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        UserLabel1.setText("Usuario");
        UserLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        UserLabel1.setIconTextGap(10);
        Bg.add(UserLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 160, -1));

        Error1Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Error1Text.setForeground(new java.awt.Color(232, 72, 85));
        Bg.add(Error1Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 190, 20));

        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitPanel.setColor(new Color(232, 72, 85));
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitPanel.setColor(new Color(75, 0, 216));
    }//GEN-LAST:event_exitLabelMouseExited

    private void exitLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitLabelMousePressed

    private void BarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_BarMousePressed

    private void BarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMouseDragged
        setLocation(
                getLocation().x + evt.getX() - mouseX,
                getLocation().y + evt.getY() - mouseY
        );
    }//GEN-LAST:event_BarMouseDragged

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        String cineName = CineField.getText();

        if (cineName.equals("")) {
            Error1Text.setText("Ingrese un nombre");
        } else {
            getUserIndex();
            LoginSystem.createCineAndMarkUserAsOld(loggedInUser, cineName);

            this.dispose();
            MainFrame MainFrame = new MainFrame(loggedInUser);
            MainFrame.setVisible(true);
        }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void CineFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CineFieldActionPerformed
    }//GEN-LAST:event_CineFieldActionPerformed

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
    }//GEN-LAST:event_UserFieldActionPerformed

    private void ImageLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageLabelMousePressed
        selectUserProfileImage(ImageLabel, loggedInUser.getUsername());
    }//GEN-LAST:event_ImageLabelMousePressed

    private void ImageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageLabelMouseEntered
        ImagePanel.setColor(new Color(48, 0, 140));
    }//GEN-LAST:event_ImageLabelMouseEntered

    private void ImageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageLabelMouseExited
        ImagePanel.setColor(new Color(75, 0, 216));
    }//GEN-LAST:event_ImageLabelMouseExited

    private void setImageLabel(JLabel label, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icon);
        this.repaint();
    }

    public void selectUserProfileImage(JLabel label, String username) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione una imagen de perfil");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Imágenes", "png", "jpg", "jpeg");
        fileChooser.addChoosableFileFilter(imageFilter);

        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String imagePath = selectedFile.getAbsolutePath();
            saveUserProfileImage(label, imagePath, username);
        }
    }

    public void saveUserProfileImage(JLabel label, String imagePath, String username) {
        String destinationPath = "CinemaCentr/usuarios/" + username + "/UserImage.png";
        File destinationFile = new File(destinationPath);
        try {
            File selectedFile = new File(imagePath);
            Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            setImageLabel(label, "CinemaCentr/usuarios/" + username + "/UserImage.png");
            System.out.println("Imagen de perfil guardada con éxito.");
        } catch (IOException e) {
            System.out.println("Error al guardar la imagen de perfil: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIresources.RoundPanel2 Bar;
    private GUIresources.RoundPanel2 Bg;
    private javax.swing.JTextField CineField;
    private javax.swing.JLabel Error1Text;
    private javax.swing.JLabel ImageLabel;
    private GUIresources.RoundPanel2 ImagePanel;
    private javax.swing.JButton StartButton;
    private javax.swing.JTextField UserField;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel UserLabel1;
    private javax.swing.JLabel exitLabel;
    private GUIresources.RoundPanel2 exitPanel;
    private javax.swing.JLabel newUserLabel;
    private javax.swing.JLabel newUserLabel1;
    // End of variables declaration//GEN-END:variables
}
