package Main;

import Experimental.GestionPeliculas;
import GUIresources.Animations;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class Dashboard extends javax.swing.JPanel {

    private MainFrame MainFrame;
    private String username;

    private ClientesSystem clientesSystem;
    private SuscripcionesSystem suscripcionesSystem;
    private SalasSystem salasSystem;


    public Dashboard(MainFrame MainFrame) {
        this.MainFrame = MainFrame;
        username = MainFrame.loggedInUser.getUsername();
        clientesSystem = new ClientesSystem(username);
        suscripcionesSystem = new SuscripcionesSystem(username);
        salasSystem = new SalasSystem(username);
        
        GestionPeliculas gestionPeliculas = new GestionPeliculas(username);
        Vector<String> nombresPeliculas = gestionPeliculas.getNamesPeli();

        initComponents();
        setImageLabel(ImageLabel, "CinemaCentr/usuarios/" + MainFrame.loggedInUser.getUsername() + "/UserImage.png");

        WelcomeLabel.setText(MainFrame.loggedInUser.getUsername() + "!");
        SummaryLabel.setText("Resumen de " + MainFrame.Cine.getName());
        SummaryLabel1.setText("Número total de peliculas:            " + nombresPeliculas.size());
        SummaryLabel2.setText("Número total de salas:            "+salasSystem.getSalasList().size());
        SummaryLabel3.setText("Número total de funciones:            " + countLines(username));
        SummaryLabel4.setText("Número total de clientes:            " + clientesSystem.getUserList().size());
        SummaryLabel5.setText("Número total de suscripciones:            " + suscripcionesSystem.getSuscripcionesList().size());

        this.setBackground(new Color(0, 0, 0, 0));
    }

    public void setImageLabel(JLabel label, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(388, 338, Image.SCALE_DEFAULT));
        label.setIcon(icon);
        this.repaint();
    }
    
    public int countLines(String username) {
    String filePath = "CinemaCentr/usuarios/" + username + "/funciones/datalist.txt";
    int lineCount = 0;

    try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
        while (reader.readLine() != null) {
            lineCount++;
        }
    } catch (IOException e) {
        System.out.println("Error al leer el archivo: " + e.getMessage());
    }

    return lineCount;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgPanel = new GUIresources.RoundPanel2();
        WelcomeLabel = new javax.swing.JLabel();
        ImagePanel = new GUIresources.RoundPanel2();
        ImageLabel = new javax.swing.JLabel();
        CinemaCentrLogo = new javax.swing.JLabel();
        SummaryLabel = new javax.swing.JLabel();
        SummaryLabel1 = new javax.swing.JLabel();
        SummaryLabel2 = new javax.swing.JLabel();
        SummaryLabel3 = new javax.swing.JLabel();
        SummaryLabel4 = new javax.swing.JLabel();
        SummaryLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BgPanel.setBottomLeftRadius(13);
        BgPanel.setBottomRightRadius(13);
        BgPanel.setColor(new java.awt.Color(255, 255, 255));
        BgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLabel.setFont(new java.awt.Font("Lato", 1, 115)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("User!");
        BgPanel.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        ImagePanel.setColor(new java.awt.Color(75, 0, 216));
        ImagePanel.setRadius(13);

        ImageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        ImagePanelLayout.setVerticalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        BgPanel.add(ImagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 400, 350));

        CinemaCentrLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CinemaCentrW.png"))); // NOI18N
        BgPanel.add(CinemaCentrLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 160, 40));

        SummaryLabel.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        SummaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        SummaryLabel.setText("Resumen de [Cine]");
        BgPanel.add(SummaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        SummaryLabel1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        SummaryLabel1.setForeground(new java.awt.Color(255, 255, 255));
        SummaryLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SummaryLabel1.setText("Número total de películas:            0 ");
        BgPanel.add(SummaryLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        SummaryLabel2.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        SummaryLabel2.setForeground(new java.awt.Color(255, 255, 255));
        SummaryLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SummaryLabel2.setText("Número total de salas:            0");
        BgPanel.add(SummaryLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 280, -1));

        SummaryLabel3.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        SummaryLabel3.setForeground(new java.awt.Color(255, 255, 255));
        SummaryLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SummaryLabel3.setText("Número total de funciones:            0");
        BgPanel.add(SummaryLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 290, -1));

        SummaryLabel4.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        SummaryLabel4.setForeground(new java.awt.Color(255, 255, 255));
        SummaryLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SummaryLabel4.setText("Número total de clientes:            0");
        BgPanel.add(SummaryLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 290, -1));

        SummaryLabel5.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        SummaryLabel5.setForeground(new java.awt.Color(255, 255, 255));
        SummaryLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SummaryLabel5.setText("Número total de suscripciones:            0");
        BgPanel.add(SummaryLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 320, -1));

        jLabel1.setFont(new java.awt.Font("Lato", 1, 63)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenid@");
        BgPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 400, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo10.png"))); // NOI18N
        BgPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        add(BgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIresources.RoundPanel2 BgPanel;
    private javax.swing.JLabel CinemaCentrLogo;
    public static javax.swing.JLabel ImageLabel;
    private GUIresources.RoundPanel2 ImagePanel;
    private javax.swing.JLabel SummaryLabel;
    private javax.swing.JLabel SummaryLabel1;
    private javax.swing.JLabel SummaryLabel2;
    private javax.swing.JLabel SummaryLabel3;
    private javax.swing.JLabel SummaryLabel4;
    private javax.swing.JLabel SummaryLabel5;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
