package Main;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author Gaco
 */
public class Login extends javax.swing.JFrame {

    //Coordenadas del mouse (variables)
    int mouseX, mouseY;
    LoginSystem LoginSystem = new LoginSystem();
    String User, Password;
    boolean ConUser, ConPassword;

    private boolean loggedIn; //Var para verificar login
    private User loggedInUser; //Guarda al usuario loggeado

    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }

    public void setLoggedInUser(User loggedInUser) {
        this.loggedInUser = loggedInUser;
    }

    public Main.User getLoggedInUser() {
        return loggedInUser;
    }

    public Login() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/AppIcon.png")).getImage());
        

        FlatLightLaf.setup();
        Bar.setBackground(new Color(0, 0, 0, 0));
        bgPanel.setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));

        LoginSystem.readUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        Bar = new javax.swing.JPanel();
        BgWhite = new GUIresources.RoundPanel2();
        UserField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        CreateAccountButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        LoginLabel = new javax.swing.JLabel();
        LockIcon = new javax.swing.JLabel();
        UserIcon = new javax.swing.JLabel();
        Error2Text = new javax.swing.JLabel();
        Error1Text = new javax.swing.JLabel();
        BgPurple = new GUIresources.RoundPanel2();
        exitlabel = new javax.swing.JLabel();
        exitpanel = new GUIresources.RoundPanel2();
        Imagotipo = new javax.swing.JLabel();
        Cinta2 = new javax.swing.JLabel();
        Cinta1 = new javax.swing.JLabel();
        VEGA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarMouseDragged(evt);
            }
        });
        Bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BarLayout = new javax.swing.GroupLayout(Bar);
        Bar.setLayout(BarLayout);
        BarLayout.setHorizontalGroup(
            BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        BarLayout.setVerticalGroup(
            BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bgPanel.add(Bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 30));

        BgWhite.setBottomLeftRadius(13);
        BgWhite.setColor(new java.awt.Color(255, 255, 255));
        BgWhite.setTopLeftRadius(13);
        BgWhite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserField.setBackground(new java.awt.Color(242, 242, 242));
        UserField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BgWhite.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 200, 30));

        PasswordField.setBackground(new java.awt.Color(242, 242, 242));
        PasswordField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BgWhite.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 200, 30));

        PasswordLabel.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel.setText("Contraseña");
        BgWhite.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        UserLabel.setBackground(new java.awt.Color(0, 0, 0));
        UserLabel.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        UserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLabel.setText("Usuario");
        BgWhite.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 80, -1));

        CreateAccountButton.setBackground(new java.awt.Color(242, 242, 242));
        CreateAccountButton.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        CreateAccountButton.setText("Crear cuenta");
        CreateAccountButton.setBorderPainted(false);
        CreateAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountButtonActionPerformed(evt);
            }
        });
        BgWhite.add(CreateAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        LoginButton.setBackground(new java.awt.Color(75, 0, 216));
        LoginButton.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Ingresar");
        LoginButton.setBorderPainted(false);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        BgWhite.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        LoginLabel.setBackground(new java.awt.Color(0, 0, 0));
        LoginLabel.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        LoginLabel.setText("Inicio de sesión");
        BgWhite.add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        LockIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/padlock.png"))); // NOI18N
        BgWhite.add(LockIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        BgWhite.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        Error2Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Error2Text.setForeground(new java.awt.Color(232, 72, 85));
        BgWhite.add(Error2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 190, 20));

        Error1Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Error1Text.setForeground(new java.awt.Color(232, 72, 85));
        BgWhite.add(Error1Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 250, 20));

        bgPanel.add(BgWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 500));

        BgPurple.setBottomRightRadius(13);
        BgPurple.setColor(new java.awt.Color(75, 0, 216));
        BgPurple.setTopRightRadius(30);
        BgPurple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitlabel.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        exitlabel.setForeground(new java.awt.Color(255, 255, 255));
        exitlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitlabel.setText("X");
        exitlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitLabelMousePressed(evt);
            }
        });
        BgPurple.add(exitlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 50, 30));

        exitpanel.setColor(new java.awt.Color(75, 0, 216));
        exitpanel.setTopRightRadius(13);

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        BgPurple.add(exitpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 50, -1));

        Imagotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagotipo 300x203.png"))); // NOI18N
        BgPurple.add(Imagotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 220));

        Cinta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/CintaPelicula.png"))); // NOI18N
        BgPurple.add(Cinta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 360, 90));

        Cinta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/CintaPelicula.png"))); // NOI18N
        BgPurple.add(Cinta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 360, 90));

        VEGA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VEGA 70x25.png"))); // NOI18N
        BgPurple.add(VEGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, 33));

        bgPanel.add(BgPurple, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 360, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_BarMousePressed

    private void BarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMouseDragged
        setLocation(
                getLocation().x + evt.getX() - mouseX,
                getLocation().y + evt.getY() - mouseY
        );
    }//GEN-LAST:event_BarMouseDragged

    private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed
        this.dispose();
        new SignIn().setVisible(true);
    }//GEN-LAST:event_CreateAccountButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        User = UserField.getText();
        Password = PasswordField.getText();

        if (User.equals("")) {
            Error1Text.setText("Ingrese un usuario");
            ConUser = false;
        } else {
            Error1Text.setText(null);
            ConUser = true;
        }

        if (Password.equals("")) {
            Error2Text.setText("Ingrese una contraseña");
            ConPassword = false;
        } else {
            Error2Text.setText(null);
            ConPassword = true;
        }

        if (ConUser && ConPassword) {
            LoginSystem.loginUser(User, Password, this);

            if (loggedIn) {
                this.dispose();
                if (loggedInUser.getState().equals("new")) {
                    CrearCine CrearCine = new CrearCine(loggedInUser);
                    CrearCine.setVisible(true);
                } else {
                    MainFrame MainFrame = new MainFrame(loggedInUser);
                    MainFrame.setVisible(true);
                }
            } else {
                Error1Text.setText("Usuario o contraseña incorrectos");
            }
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void exitLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitLabelMousePressed

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitpanel.setColor(new Color(75, 0, 216));
    }//GEN-LAST:event_exitLabelMouseExited

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitpanel.setColor(new Color(232,72,85));
    }//GEN-LAST:event_exitLabelMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UIManager.put( "Component.arc", 999 );
        UIManager.put("TextComponent.arc", 999);
        UIManager.put("Button.arc", 999);
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main.Splash(null, true).setVisible(true);
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bar;
    private GUIresources.RoundPanel2 BgPurple;
    private GUIresources.RoundPanel2 BgWhite;
    private javax.swing.JLabel Cinta1;
    private javax.swing.JLabel Cinta2;
    private javax.swing.JButton CreateAccountButton;
    private javax.swing.JLabel Error1Text;
    private javax.swing.JLabel Error2Text;
    private javax.swing.JLabel Imagotipo;
    private javax.swing.JLabel LockIcon;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField UserField;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel VEGA;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel exitlabel;
    private GUIresources.RoundPanel2 exitpanel;
    // End of variables declaration//GEN-END:variables

}
