package Main;

import java.awt.Color;

/**
 *
 * @author Gaco
 */
public class NewAccount extends javax.swing.JDialog {

    //Coordenadas del mouse (variables)
    int mouseX, mouseY;

    public NewAccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setBackground(new Color(0, 0, 0, 0));
        Bar.setBackground(new Color(0, 0, 0, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel21 = new GUIresources.RoundPanel2();
        ExitButton = new javax.swing.JButton();
        newUserLabel2 = new javax.swing.JLabel();
        Bar = new javax.swing.JPanel();
        newUserLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        roundPanel21.setColor(new java.awt.Color(234, 234, 234));
        roundPanel21.setRadius(13);
        roundPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitButton.setBackground(new java.awt.Color(75, 0, 216));
        ExitButton.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Confirmar");
        ExitButton.setBorderPainted(false);
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        roundPanel21.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, -1));

        newUserLabel2.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        newUserLabel2.setForeground(new java.awt.Color(56, 48, 46));
        newUserLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/agregar-usuario.png"))); // NOI18N
        newUserLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        newUserLabel2.setIconTextGap(10);
        roundPanel21.add(newUserLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 30, 130, 130));

        Bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarMouseDragged(evt);
            }
        });
        Bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BarLayout = new javax.swing.GroupLayout(Bar);
        Bar.setLayout(BarLayout);
        BarLayout.setHorizontalGroup(
            BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        BarLayout.setVerticalGroup(
            BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        roundPanel21.add(Bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 20));

        newUserLabel3.setFont(new java.awt.Font("Lato", 1, 22)); // NOI18N
        newUserLabel3.setForeground(new java.awt.Color(56, 48, 46));
        newUserLabel3.setText("Usuario registrado");
        newUserLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        newUserLabel3.setIconTextGap(10);
        roundPanel21.add(newUserLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void BarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMouseDragged
        setLocation(
                getLocation().x + evt.getX() - mouseX,
                getLocation().y + evt.getY() - mouseY
        );
    }//GEN-LAST:event_BarMouseDragged

    private void BarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_BarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewAccount dialog = new NewAccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bar;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel newUserLabel2;
    private javax.swing.JLabel newUserLabel3;
    private GUIresources.RoundPanel2 roundPanel21;
    // End of variables declaration//GEN-END:variables
}
