package Main;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author Gaco
 */
public class SignIn extends javax.swing.JFrame {

    //Coordenadas del mouse (variables)
    int mouseX, mouseY;
    LoginSystem LoginSystem = new LoginSystem();
    String User, Password, ConfPassword;
    boolean ConUser, ConPassword;

    public SignIn() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/AppIcon.png")).getImage());

        FlatLightLaf.setup();
        Bar.setBackground(new Color(0, 0, 0, 0));
        bgPanel.setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));

        LoginSystem.readUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        Bar = new javax.swing.JPanel();
        roundPanel22 = new GUIresources.RoundPanel2();
        Imagotipo = new javax.swing.JLabel();
        CintaImagen = new javax.swing.JLabel();
        Cinta2Imagen = new javax.swing.JLabel();
        VEGA = new javax.swing.JLabel();
        exitpanel = new GUIresources.RoundPanel2();
        exitlabel = new javax.swing.JLabel();
        BgWhite = new GUIresources.RoundPanel2();
        RegisterLabel = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        UserIcon = new javax.swing.JLabel();
        ConfirmLabel = new javax.swing.JLabel();
        LockIcon = new javax.swing.JLabel();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        RegisterButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Error2Text = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        Error1Text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarMouseDragged(evt);
            }
        });
        Bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BarLayout = new javax.swing.GroupLayout(Bar);
        Bar.setLayout(BarLayout);
        BarLayout.setHorizontalGroup(
            BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        BarLayout.setVerticalGroup(
            BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bgPanel.add(Bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 30));

        roundPanel22.setBottomRightRadius(13);
        roundPanel22.setColor(new java.awt.Color(75, 0, 216));
        roundPanel22.setTopRightRadius(30);
        roundPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagotipo 300x203.png"))); // NOI18N
        roundPanel22.add(Imagotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 220));

        CintaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/CintaPelicula.png"))); // NOI18N
        roundPanel22.add(CintaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 360, 90));

        Cinta2Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/CintaPelicula.png"))); // NOI18N
        roundPanel22.add(Cinta2Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 360, 90));

        VEGA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VEGA 70x25.png"))); // NOI18N
        roundPanel22.add(VEGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, 33));

        exitpanel.setColor(new java.awt.Color(75, 0, 216));
        exitpanel.setTopRightRadius(13);

        exitlabel.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        exitlabel.setForeground(new java.awt.Color(255, 255, 255));
        exitlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitlabel.setText("X");
        exitlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitlabelexitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitlabelexitLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitlabelexitLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundPanel22.add(exitpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 50, -1));

        bgPanel.add(roundPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 360, 500));

        BgWhite.setBottomLeftRadius(13);
        BgWhite.setTopLeftRadius(13);
        BgWhite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterLabel.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        RegisterLabel.setForeground(new java.awt.Color(56, 48, 46));
        RegisterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterLabel.setText("Crear cuenta");
        RegisterLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BgWhite.add(RegisterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 140, -1));

        UserLabel.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(56, 48, 46));
        UserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLabel.setText("Usuario");
        UserLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BgWhite.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 80, -1));

        UserField.setBackground(new java.awt.Color(242, 242, 242));
        UserField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        BgWhite.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 200, 30));

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        BgWhite.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        ConfirmLabel.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        ConfirmLabel.setForeground(new java.awt.Color(56, 48, 46));
        ConfirmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConfirmLabel.setText("Confirmar contraseña");
        BgWhite.add(ConfirmLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 180, -1));

        LockIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/padlock.png"))); // NOI18N
        BgWhite.add(LockIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        ConfirmPasswordField.setBackground(new java.awt.Color(242, 242, 242));
        ConfirmPasswordField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordFieldActionPerformed(evt);
            }
        });
        BgWhite.add(ConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 200, 30));

        RegisterButton.setBackground(new java.awt.Color(75, 0, 216));
        RegisterButton.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Registrarse");
        RegisterButton.setBorderPainted(false);
        RegisterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        BgWhite.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        BackButton.setBackground(new java.awt.Color(242, 242, 242));
        BackButton.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        BackButton.setForeground(new java.awt.Color(56, 48, 46));
        BackButton.setText("Volver");
        BackButton.setBorderPainted(false);
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        BgWhite.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 90, -1));

        Error2Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Error2Text.setForeground(new java.awt.Color(232, 72, 85));
        BgWhite.add(Error2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 240, 20));

        PasswordField.setBackground(new java.awt.Color(242, 242, 242));
        PasswordField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BgWhite.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 200, 30));

        PasswordLabel.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(56, 48, 46));
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel.setText("Contraseña");
        BgWhite.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 220, 100, -1));

        Error1Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Error1Text.setForeground(new java.awt.Color(232, 72, 85));
        BgWhite.add(Error1Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 200, 20));

        bgPanel.add(BgWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMouseDragged
        setLocation(
                getLocation().x + evt.getX() - mouseX,
                getLocation().y + evt.getY() - mouseY
        );
    }//GEN-LAST:event_BarMouseDragged

    private void BarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_BarMousePressed

    private void exitlabelexitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabelexitLabelMouseEntered
        exitpanel.setColor(new Color(232, 72, 85));
    }//GEN-LAST:event_exitlabelexitLabelMouseEntered

    private void exitlabelexitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabelexitLabelMouseExited
        exitpanel.setColor(new Color(75, 0, 216));
    }//GEN-LAST:event_exitlabelexitLabelMouseExited

    private void exitlabelexitLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabelexitLabelMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitlabelexitLabelMousePressed

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        User = UserField.getText();
        Password = PasswordField.getText();
        ConfPassword = ConfirmPasswordField.getText();

        if (Password.equals("")) {
            Error2Text.setText("Ingrese una contraseña");
            ConPassword = false;
        } else {
            if (!Password.equals(ConfPassword)) {
                Error2Text.setText("Las contraseñas deben ser iguales");
                ConPassword = false;
            } else {
                Error2Text.setText(null);
                ConPassword = true;
            }
        }
        if (User.equals("")) {
            Error1Text.setText("Ingrese un usuario");
            ConUser = false;
        } else {
            Error1Text.setText(null);
            ConUser = true;
        }

        if (ConUser && ConPassword) {
            LoginSystem.createUser(User, Password, Error1Text, UserField, PasswordField, ConfirmPasswordField, new NewAccount(this,true));
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UIManager.put("TextComponent.arc", 999);
        UIManager.put("Button.arc", 999);
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main.Splash(null, true).setVisible(true);
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Bar;
    private GUIresources.RoundPanel2 BgWhite;
    private javax.swing.JLabel Cinta2Imagen;
    private javax.swing.JLabel CintaImagen;
    private javax.swing.JLabel ConfirmLabel;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel Error1Text;
    private javax.swing.JLabel Error2Text;
    private javax.swing.JLabel Imagotipo;
    private javax.swing.JLabel LockIcon;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JTextField UserField;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel VEGA;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel exitlabel;
    private GUIresources.RoundPanel2 exitpanel;
    private GUIresources.RoundPanel2 roundPanel22;
    // End of variables declaration//GEN-END:variables
}
