package Main;

import java.awt.Color;
import java.awt.Font;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Gaco
 */
public class Clientes extends javax.swing.JPanel {

    private DefaultTableModel clientesModel;
    private DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

    private MainFrame MainFrame;
    private String username;
    String nombre, correo, telefono, id, suscripcion;
    int suscripcionIndex;
    boolean ConNombre, ConCorreo, ConTelefono, ConId, ConSuscripcion;

    private ClientesSystem clientesSystem;
    List<Cliente> clientesList;

    private SuscripcionesSystem suscripcionesSystem;
    List<Suscripcion> suscripcionesList;

    public void updateTable() {
        clientesModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Desactivar la edición de todas las celdas
            }
        };

        clientesModel.addColumn("Nombre");
        clientesModel.addColumn("Correo");
        clientesModel.addColumn("Teléfono");
        clientesModel.addColumn("ID");
        clientesModel.addColumn("Suscripción");

        Collections.sort(clientesList, Comparator.comparing(Cliente::getSuscripcion));
        
        // Agregar los datos de los clientes al modelo de la tabla
        for (Cliente cliente : clientesList) {
            Object[] rowData = {cliente.getNombre(), cliente.getCorreo(), cliente.getTelefono(), cliente.getId(), cliente.getSuscripcion()};
            clientesModel.addRow(rowData);
        }
    }

    public void setComboModel() {
        // Recorrer el arreglo de suscripciones y obtener los nombres
        for (Suscripcion suscripcion : suscripcionesList) {
            String nombreSuscripcion = suscripcion.getNombre();
            comboBoxModel.addElement(nombreSuscripcion);
        }
    }

    public Clientes(MainFrame MainFrame) {
        this.MainFrame = MainFrame;
        username = MainFrame.loggedInUser.getUsername();
        clientesSystem = new ClientesSystem(username);
        clientesList = clientesSystem.getUserList();
        suscripcionesSystem = new SuscripcionesSystem(username);
        suscripcionesList = suscripcionesSystem.getSuscripcionesList();

        setComboModel();
        updateTable();

        initComponents();

        SuscripcionesBox.setModel(comboBoxModel);

        JTableHeader header = ClientesTable.getTableHeader();
        Font headerFont = new Font("Roboto", Font.PLAIN, 18);
        header.setFont(headerFont);
        ClientesTable.setModel(clientesModel);

        this.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgPanel = new GUIresources.RoundPanel2();
        RegistrarButton = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        CorreoField = new javax.swing.JTextField();
        TelefonoField = new javax.swing.JTextField();
        IdField = new javax.swing.JTextField();
        SuscripcionesBox = new javax.swing.JComboBox<>();
        Error1Text = new javax.swing.JLabel();
        Error2Text = new javax.swing.JLabel();
        Error3Text = new javax.swing.JLabel();
        Error4Text = new javax.swing.JLabel();
        Error5Text = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        ClientesTable = new javax.swing.JTable();
        DeleteUser = new javax.swing.JButton();
        AgregarClienteLabel = new javax.swing.JLabel();
        ClientesLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        CorreoLabel = new javax.swing.JLabel();
        TelefonoLabel = new javax.swing.JLabel();
        IdLabel = new javax.swing.JLabel();
        IdLabel1 = new javax.swing.JLabel();
        grayBgPanel = new GUIresources.RoundPanel2();

        BgPanel.setBottomLeftRadius(13);
        BgPanel.setBottomRightRadius(13);
        BgPanel.setColor(new java.awt.Color(255, 255, 255));
        BgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrarButton.setBackground(new java.awt.Color(75, 0, 216));
        RegistrarButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        RegistrarButton.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarButton.setText("Registrar cliente");
        RegistrarButton.setBorderPainted(false);
        RegistrarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarButtonActionPerformed(evt);
            }
        });
        BgPanel.add(RegistrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 200, -1));

        NameField.setBackground(new java.awt.Color(255, 255, 255));
        NameField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        NameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameFieldKeyTyped(evt);
            }
        });
        BgPanel.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 20));

        CorreoField.setBackground(new java.awt.Color(255, 255, 255));
        CorreoField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        CorreoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoFieldActionPerformed(evt);
            }
        });
        BgPanel.add(CorreoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 20));

        TelefonoField.setBackground(new java.awt.Color(255, 255, 255));
        TelefonoField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TelefonoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoFieldActionPerformed(evt);
            }
        });
        TelefonoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoFieldKeyTyped(evt);
            }
        });
        BgPanel.add(TelefonoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, 20));

        IdField.setBackground(new java.awt.Color(255, 255, 255));
        IdField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        IdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFieldActionPerformed(evt);
            }
        });
        IdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdFieldKeyTyped(evt);
            }
        });
        BgPanel.add(IdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 200, 20));

        SuscripcionesBox.setBackground(new java.awt.Color(255, 255, 255));
        SuscripcionesBox.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        SuscripcionesBox.setMaximumRowCount(20);
        SuscripcionesBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BgPanel.add(SuscripcionesBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 200, -1));

        Error1Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Error1Text.setForeground(new java.awt.Color(232, 72, 85));
        BgPanel.add(Error1Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 20));

        Error2Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Error2Text.setForeground(new java.awt.Color(232, 72, 85));
        BgPanel.add(Error2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, 20));

        Error3Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Error3Text.setForeground(new java.awt.Color(232, 72, 85));
        BgPanel.add(Error3Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 260, 20));

        Error4Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Error4Text.setForeground(new java.awt.Color(232, 72, 85));
        BgPanel.add(Error4Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 220, 20));

        Error5Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Error5Text.setForeground(new java.awt.Color(232, 72, 85));
        BgPanel.add(Error5Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 220, 20));

        ClientesTable.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ClientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ClientesTable.setFocusable(false);
        ClientesTable.setSelectionBackground(new java.awt.Color(232, 72, 85));
        ClientesTable.setShowHorizontalLines(true);
        ScrollPane.setViewportView(ClientesTable);

        BgPanel.add(ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 680, 450));

        DeleteUser.setBackground(new java.awt.Color(232, 72, 85));
        DeleteUser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        DeleteUser.setForeground(new java.awt.Color(255, 255, 255));
        DeleteUser.setText("Eliminar cliente");
        DeleteUser.setBorderPainted(false);
        DeleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserActionPerformed(evt);
            }
        });
        BgPanel.add(DeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, 160, -1));

        AgregarClienteLabel.setFont(new java.awt.Font("Roboto Medium", 0, 22)); // NOI18N
        AgregarClienteLabel.setForeground(new java.awt.Color(56, 48, 46));
        AgregarClienteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/agregar-usuario24px.png"))); // NOI18N
        AgregarClienteLabel.setText("Agregar cliente");
        AgregarClienteLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AgregarClienteLabel.setIconTextGap(10);
        BgPanel.add(AgregarClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, -1));

        ClientesLabel.setFont(new java.awt.Font("Roboto Medium", 0, 22)); // NOI18N
        ClientesLabel.setForeground(new java.awt.Color(56, 48, 46));
        ClientesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/usuarios-alt.png"))); // NOI18N
        ClientesLabel.setText("Clientes");
        ClientesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ClientesLabel.setIconTextGap(10);
        BgPanel.add(ClientesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 120, -1));

        NombreLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(56, 48, 46));
        NombreLabel.setText("Nombre");
        NombreLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        NombreLabel.setIconTextGap(10);
        BgPanel.add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, -1));

        CorreoLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        CorreoLabel.setForeground(new java.awt.Color(56, 48, 46));
        CorreoLabel.setText("Correo");
        CorreoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CorreoLabel.setIconTextGap(10);
        BgPanel.add(CorreoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        TelefonoLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TelefonoLabel.setForeground(new java.awt.Color(56, 48, 46));
        TelefonoLabel.setText("Teléfono");
        TelefonoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        TelefonoLabel.setIconTextGap(10);
        BgPanel.add(TelefonoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, -1));

        IdLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        IdLabel.setForeground(new java.awt.Color(56, 48, 46));
        IdLabel.setText("Identificación");
        IdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        IdLabel.setIconTextGap(10);
        BgPanel.add(IdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 110, -1));

        IdLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        IdLabel1.setForeground(new java.awt.Color(56, 48, 46));
        IdLabel1.setText("Suscripción");
        IdLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        IdLabel1.setIconTextGap(10);
        BgPanel.add(IdLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 110, -1));

        grayBgPanel.setBackground(new java.awt.Color(242, 242, 242));
        grayBgPanel.setColor(new java.awt.Color(242, 242, 242));
        grayBgPanel.setRadius(13);

        javax.swing.GroupLayout grayBgPanelLayout = new javax.swing.GroupLayout(grayBgPanel);
        grayBgPanel.setLayout(grayBgPanelLayout);
        grayBgPanelLayout.setHorizontalGroup(
            grayBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        grayBgPanelLayout.setVerticalGroup(
            grayBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        BgPanel.add(grayBgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 970, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarButtonActionPerformed
        nombre = NameField.getText();
        correo = CorreoField.getText();
        telefono = TelefonoField.getText();
        id = IdField.getText();
        suscripcionIndex = SuscripcionesBox.getSelectedIndex();
        
        if (nombre.equals("")) {
            Error1Text.setText("Ingrese un nombre");
            ConNombre = false;
        } else {
            Error1Text.setText(null);
            ConNombre = true;
        }

        if (correo.equals("")) {
            Error2Text.setText("Ingrese un correo");
            ConCorreo = false;
        } else {
            Error2Text.setText(null);
            ConCorreo = true;
        }

        if (telefono.equals("")) {
            Error3Text.setText("Ingrese un telefono");
            ConTelefono = false;
        } else {
            Error3Text.setText(null);
            ConTelefono = true;
        }

        if (id.equals("")) {
            Error4Text.setText("Ingrese una identificación");
            ConId = false;
        } else {
            Error4Text.setText(null);
            ConId = true;
        }

        if (suscripcionIndex == -1) {
            Error5Text.setText("No hay suscripciones");
            ConSuscripcion = false;
        } else {
            Error5Text.setText(null);
            suscripcion = (String) SuscripcionesBox.getSelectedItem();
            System.out.println(suscripcion);
            ConSuscripcion = true;
        }

        if (ConNombre && ConCorreo && ConTelefono && ConId && ConSuscripcion) {
            clientesSystem.createCliente(username, nombre, correo, telefono, id, suscripcion, Error2Text, Error3Text, Error4Text, NameField, CorreoField, TelefonoField, IdField);
            updateTable();
            ClientesTable.setModel(clientesModel);
        }
    }//GEN-LAST:event_RegistrarButtonActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void CorreoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoFieldActionPerformed

    private void TelefonoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoFieldActionPerformed

    private void IdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFieldActionPerformed

    private void TelefonoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoFieldKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoFieldKeyTyped

    private void IdFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdFieldKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_IdFieldKeyTyped

    private void NameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameFieldKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_NameFieldKeyTyped

    private void DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserActionPerformed
        // Obtener la fila seleccionada

        int selectedRow = ClientesTable.getSelectedRow();
        System.out.println(selectedRow);

        // Verificar si hay una fila seleccionada
        if (selectedRow != -1) {
            // Obtener el cliente correspondiente a la fila seleccionada
            Cliente clienteSeleccionado = clientesList.get(selectedRow);

            // Eliminar el cliente del arreglo y del archivo
            clientesSystem.removeCliente(clienteSeleccionado);
            clientesList.remove(clienteSeleccionado);

            updateTable();
            ClientesTable.setModel(clientesModel);
            System.out.println("Cliente eliminado");
        } else {
            System.out.println("No hay fila seleccionada");
        }

    }//GEN-LAST:event_DeleteUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarClienteLabel;
    private GUIresources.RoundPanel2 BgPanel;
    private javax.swing.JLabel ClientesLabel;
    private javax.swing.JTable ClientesTable;
    private javax.swing.JTextField CorreoField;
    private javax.swing.JLabel CorreoLabel;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JLabel Error1Text;
    private javax.swing.JLabel Error2Text;
    private javax.swing.JLabel Error3Text;
    private javax.swing.JLabel Error4Text;
    private javax.swing.JLabel Error5Text;
    private javax.swing.JTextField IdField;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JLabel IdLabel1;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JButton RegistrarButton;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JComboBox<String> SuscripcionesBox;
    private javax.swing.JTextField TelefonoField;
    private javax.swing.JLabel TelefonoLabel;
    private GUIresources.RoundPanel2 grayBgPanel;
    // End of variables declaration//GEN-END:variables
}
