package Main;

import Experimental.GestionPeliculas;
import GUIresources.Animations;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class Dashboard extends javax.swing.JPanel {

    private MainFrame MainFrame;
    private String username;

    private ClientesSystem clientesSystem;
    private SuscripcionesSystem suscripcionesSystem;


    public Dashboard(MainFrame MainFrame) {
        this.MainFrame = MainFrame;
        username = MainFrame.loggedInUser.getUsername();
        clientesSystem = new ClientesSystem(username);
        suscripcionesSystem = new SuscripcionesSystem(username);
        
        GestionPeliculas gestionPeliculas = new GestionPeliculas(username);
        Vector<String> nombresPeliculas = gestionPeliculas.getNamesPeli();

        initComponents();
        setImageLabel(ImageLabel, "CinemaCentr/usuarios/" + MainFrame.loggedInUser.getUsername() + "/UserImage.png");

        WelcomeLabel.setText("Bienvenido " + MainFrame.loggedInUser.getUsername());
        SummaryLabel.setText("Resumen de " + MainFrame.Cine.getName());
        SummaryLabel1.setText("Número total de peliculas:  " + nombresPeliculas.size());

        SummaryLabel4.setText("Número total de clientes:  " + clientesSystem.getUserList().size());
        SummaryLabel5.setText("Número total de suscripciones:  " + suscripcionesSystem.getSuscripcionesList().size());

        this.setBackground(new Color(0, 0, 0, 0));
    }

    public void setImageLabel(JLabel label, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(258, 258, Image.SCALE_DEFAULT));
        label.setIcon(icon);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgPanel = new GUIresources.RoundPanel2();
        WelcomeLabel = new javax.swing.JLabel();
        ImagePanel = new GUIresources.RoundPanel2();
        ImageLabel = new javax.swing.JLabel();
        CinemaCentrLogo = new javax.swing.JLabel();
        SummaryLabel = new javax.swing.JLabel();
        roundPanel21 = new GUIresources.RoundPanel2();
        SummaryLabel1 = new javax.swing.JLabel();
        SummaryLabel2 = new javax.swing.JLabel();
        SummaryLabel3 = new javax.swing.JLabel();
        SummaryLabel4 = new javax.swing.JLabel();
        SummaryLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BgPanel.setBottomLeftRadius(13);
        BgPanel.setBottomRightRadius(13);
        BgPanel.setColor(new java.awt.Color(255, 255, 255));
        BgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLabel.setFont(new java.awt.Font("Roboto Medium", 0, 72)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(75, 0, 216));
        WelcomeLabel.setText("Bienvenido User");
        BgPanel.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        ImagePanel.setColor(new java.awt.Color(75, 0, 216));
        ImagePanel.setRadius(13);

        ImageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        ImagePanelLayout.setVerticalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        BgPanel.add(ImagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 270, 270));

        CinemaCentrLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CinemaCentrP.png"))); // NOI18N
        BgPanel.add(CinemaCentrLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 320, 220, 40));

        SummaryLabel.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        SummaryLabel.setForeground(new java.awt.Color(56, 48, 46));
        SummaryLabel.setText("Resumen de [Cine]");
        BgPanel.add(SummaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 150, -1, -1));

        roundPanel21.setColor(new java.awt.Color(242, 242, 242));
        roundPanel21.setRadius(13);

        SummaryLabel1.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        SummaryLabel1.setForeground(new java.awt.Color(56, 48, 46));
        SummaryLabel1.setText("Número total de películas:  0 ");

        SummaryLabel2.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        SummaryLabel2.setForeground(new java.awt.Color(56, 48, 46));
        SummaryLabel2.setText("Número total de salas:  0");

        SummaryLabel3.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        SummaryLabel3.setForeground(new java.awt.Color(56, 48, 46));
        SummaryLabel3.setText("Número total de funciones:  0");

        SummaryLabel4.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        SummaryLabel4.setForeground(new java.awt.Color(56, 48, 46));
        SummaryLabel4.setText("Número total de clientes:  0");

        SummaryLabel5.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        SummaryLabel5.setForeground(new java.awt.Color(56, 48, 46));
        SummaryLabel5.setText("Número total de suscripciones:  0");

        javax.swing.GroupLayout roundPanel21Layout = new javax.swing.GroupLayout(roundPanel21);
        roundPanel21.setLayout(roundPanel21Layout);
        roundPanel21Layout.setHorizontalGroup(
            roundPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SummaryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SummaryLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SummaryLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SummaryLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SummaryLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        roundPanel21Layout.setVerticalGroup(
            roundPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel21Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(SummaryLabel1)
                .addGap(22, 22, 22)
                .addComponent(SummaryLabel2)
                .addGap(22, 22, 22)
                .addComponent(SummaryLabel3)
                .addGap(22, 22, 22)
                .addComponent(SummaryLabel4)
                .addGap(22, 22, 22)
                .addComponent(SummaryLabel5)
                .addGap(17, 17, 17))
        );

        BgPanel.add(roundPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 550, 380));

        add(BgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIresources.RoundPanel2 BgPanel;
    private javax.swing.JLabel CinemaCentrLogo;
    public static javax.swing.JLabel ImageLabel;
    private GUIresources.RoundPanel2 ImagePanel;
    private javax.swing.JLabel SummaryLabel;
    private javax.swing.JLabel SummaryLabel1;
    private javax.swing.JLabel SummaryLabel2;
    private javax.swing.JLabel SummaryLabel3;
    private javax.swing.JLabel SummaryLabel4;
    private javax.swing.JLabel SummaryLabel5;
    private javax.swing.JLabel WelcomeLabel;
    private GUIresources.RoundPanel2 roundPanel21;
    // End of variables declaration//GEN-END:variables
}
