package Main;

import GUIresources.Animations;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author Gaco
 */
public class Movies extends javax.swing.JPanel {

    Animations Animations = new Animations();

    public Movies() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgPanel = new GUIresources.RoundPanel2();
        jLabel1 = new javax.swing.JLabel();

        BgPanel.setBottomLeftRadius(13);
        BgPanel.setBottomRightRadius(13);
        BgPanel.setColor(new java.awt.Color(242, 242, 242));
        BgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 60)); // NOI18N
        jLabel1.setText("Películas");
        BgPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIresources.RoundPanel2 BgPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
