package Main;

import GUIresources.Animations;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class Salas extends javax.swing.JPanel {

    Animations Animations = new Animations();
    DefaultTableModel tableModel;
    String archivo = "salas.txt";
    private String usuario;

    public Salas(String usuario) {
        this.usuario = usuario;
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        tableModel = (DefaultTableModel) Tabla.getModel();
        try (BufferedReader br = new BufferedReader(new FileReader("CinemaCentr/usuarios/" + usuario + "/salas.txt"))) {
            String line;

            while ((line = br.readLine()) != null) {
                String[] columns = line.split(",");
                String nombre = columns[0];
                int rows = Integer.parseInt(columns[1]);
                int cols = Integer.parseInt(columns[2]);
                    Object[] rowData = {nombre, rows, cols};
                    tableModel.addRow(rowData);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgPanel = new GUIresources.RoundPanel2();
        jLabel2 = new javax.swing.JLabel();
        NumCol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NameSala = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NumFil = new javax.swing.JTextField();
        MasSala = new javax.swing.JButton();
        MenosSala = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        BgPanel.setBottomLeftRadius(13);
        BgPanel.setBottomRightRadius(13);
        BgPanel.setColor(new java.awt.Color(242, 242, 242));
        BgPanel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BgPanel.setInheritsPopupMenu(true);
        BgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Filas de Asientos:");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 18));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 18));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 18));
        BgPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 120, 20));

        NumCol.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NumCol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumCol.setBorder(null);
        NumCol.setMaximumSize(new java.awt.Dimension(120, 18));
        NumCol.setMinimumSize(new java.awt.Dimension(120, 18));
        NumCol.setPreferredSize(new java.awt.Dimension(120, 18));
        NumCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumColActionPerformed(evt);
            }
        });
        BgPanel.add(NumCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Columnas de Asientos:");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 18));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 18));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 18));
        BgPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 150, 20));

        NameSala.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NameSala.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NameSala.setBorder(null);
        NameSala.setMaximumSize(new java.awt.Dimension(120, 18));
        NameSala.setMinimumSize(new java.awt.Dimension(120, 18));
        NameSala.setPreferredSize(new java.awt.Dimension(120, 18));
        NameSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameSalaActionPerformed(evt);
            }
        });
        BgPanel.add(NameSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre de la Sala:");
        jLabel4.setMaximumSize(new java.awt.Dimension(120, 18));
        jLabel4.setMinimumSize(new java.awt.Dimension(120, 18));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 18));
        BgPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 130, 20));

        NumFil.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NumFil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumFil.setBorder(null);
        NumFil.setMaximumSize(new java.awt.Dimension(120, 18));
        NumFil.setMinimumSize(new java.awt.Dimension(120, 18));
        NumFil.setPreferredSize(new java.awt.Dimension(120, 18));
        NumFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumFilActionPerformed(evt);
            }
        });
        BgPanel.add(NumFil, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, 20));

        MasSala.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        MasSala.setText("Añadir Sala");
        MasSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasSalaActionPerformed(evt);
            }
        });
        BgPanel.add(MasSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 140, 50));

        MenosSala.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        MenosSala.setText("Eliminar Sala");
        MenosSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosSalaActionPerformed(evt);
            }
        });
        BgPanel.add(MenosSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 140, 50));

        Tabla.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Filas", "Columnas"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        BgPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NumColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumColActionPerformed

    private void NameSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameSalaActionPerformed

    private void NumFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumFilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumFilActionPerformed

    private void MasSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasSalaActionPerformed
        String name = NameSala.getText();
        int rows = Integer.parseInt(NumFil.getText());
        int cols = Integer.parseInt(NumCol.getText());
        Object[] rowData = {name, rows, cols};
        tableModel.addRow(rowData);

        try (BufferedWriter writer = new BufferedWriter(new FileWriter("CinemaCentr/usuarios/" + usuario + "/salas.txt", true))) {
            // Escribir los datos en el archivo separados por comas
            writer.write(name + "," + rows + "," + cols);
            writer.newLine(); // Agregar una nueva línea
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Clear input fields
        NameSala.setText("");
        NumFil.setText("");
        NumCol.setText("");
    }//GEN-LAST:event_MasSalaActionPerformed

    private void MenosSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosSalaActionPerformed
        int selectedRow = Tabla.getSelectedRow();
        if (selectedRow != -1) {
            tableModel.removeRow(selectedRow);
        }
    }//GEN-LAST:event_MenosSalaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIresources.RoundPanel2 BgPanel;
    private javax.swing.JButton MasSala;
    private javax.swing.JButton MenosSala;
    private javax.swing.JTextField NameSala;
    private javax.swing.JTextField NumCol;
    private javax.swing.JTextField NumFil;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
